import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <title>BIT</title>
      <link rel="icon" type="image/x-icon" href={"/images/Bit.png"}></link>
      <body className={`${inter.className} w-full bg-bitBrown`}>
        {children}
      </body>
    </html>
  );
}
